// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkOrderTracker.Api.Data;

#nullable disable

namespace WorkOrderTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderTracker.Api.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "120 Harbor St",
                            Name = "Harbor View Apartments"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Elm St",
                            Name = "Elm Street Offices"
                        });
                });

            modelBuilder.Entity("WorkOrderTracker.Api.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Trade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sam.rivera@example.com",
                            Name = "Sam Rivera",
                            Trade = "HVAC"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jordan.lee@example.com",
                            Name = "Jordan Lee",
                            Trade = "Plumbing"
                        });
                });

            modelBuilder.Entity("WorkOrderTracker.Api.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            CreatedAt = new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Unit 4B",
                            Priority = "High",
                            Status = "InProgress",
                            TechnicianId = 1,
                            Title = "AC not cooling"
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 2,
                            CreatedAt = new DateTime(2026, 10, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Location = "3rd floor kitchen",
                            Priority = "Medium",
                            Status = "Open",
                            Title = "Leaking sink in break room"
                        });
                });

            modelBuilder.Entity("WorkOrderTracker.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderTracker.Api.Models.Building", "Building")
                        .WithMany("WorkOrders")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderTracker.Api.Models.Technician", "Technician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("WorkOrderTracker.Api.Models.Building", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderTracker.Api.Models.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
